services:
  - type: web
    name: fdc-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn server:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: API_KEY
        sync: false # Will prompt you to enter this in Render dashboard
    disk:
      name: fdc_data
      mountPath: /var/lib/data
      sizeGB: 1
